# The program generates a list which is generated by adding the digits of the 
# elements present in the main list 

# Let us assume that all the original elements of the list are integers

# 1. The method uses loops

def usingLoops(arr):
    lst = []

    for i in arr:
        s = 0
        while i != 0:
            s += (i % 10)
            i //= 10

        lst.append(s)

    return lst 

print(usingLoops([123, 3456, 789, 0]))


'''
THIS IS AN ALTERNATE CODE SNIPPET USING LIST COMPREHNSION FROM GEEKS FOR GEEKS

a = [123, 456, 789]
res = [sum(int(digit) for digit in str(val)) for val in a]
print(res)

'''
