# the script is just to test the subject list 

from subjectList import subjectList 


s = subjectList()
while True:
    print("add subject")
    id = input("enter id : ")
    sub = input("enter sub : ")
    s.addSubject(id, sub)
    print("add subject")
    id = input("enter id : ")
    sub = input("enter sub : ")
    s.addSubject(id, sub)
    print("add subject")
    id = input("enter id : ")
    sub = input("enter sub : ")
    s.addSubject(id, sub)
    print("add subject")
    id = input("enter id : ")
    sub = input("enter sub : ")
    s.addSubject(id, sub)
    print("add subject")
    id = input("enter id : ")
    sub = input("enter sub : ")
    s.addSubject(id, sub)
    s.viewSubjectList()
    print('-' * 50)
    print("edit subject")
    id = input("enter id:")
    subname = input("enter sub name:")
    s.editSubject(id, subname)
    print("edit subject")
    id = input("enter id:")
    subname = input("enter sub name:")
    s.editSubject(id, subname)
    print("edit subject")
    id = input("enter id:")
    subname = input("enter sub name:")
    s.editSubject(id, subname)
    s.viewSubjectList()
    print('-' * 50)
    de = input("Enter whether delete by id(I) or by subject(S)").upper()
    s.deleteSubject(de)
    de = input("Enter whether delete by id(I) or by subject(S)").upper()
    s.deleteSubject(de)
    de = input("Enter whether delete by id(I) or by subject(S)").upper()
    s.deleteSubject(de)
    s.viewSubjectList()
    print('-' * 50)
    idfind = input("enter subject id to be found:")
    print(s.findSubject(idfind))
    idfind = input("enter subject id to be found:")
    print(s.findSubject(idfind))
    idfind = input("enter subject id to be found:")
    print(s.findSubject(idfind))
    s.viewSubjectList()
    print('-' * 50)